declare const __DEV__: boolean;

declare namespace NodeJS {
  interface ProcessEnv {
    EXPO_PUBLIC_REVENUECAT_PUBLIC_SDK_KEY?: string;
    EXPO_PUBLIC_REVENUECAT_APPLE_API_KEY?: string;
    EXPO_PUBLIC_REVENUECAT_GOOGLE_API_KEY?: string;
    EXPO_PUBLIC_REVENUECAT_ENTITLEMENT_ID?: string;
    EXPO_PUBLIC_REVENUECAT_MONTHLY_PRODUCT_ID?: string;
    EXPO_PUBLIC_REVENUECAT_MONTHLY_PACKAGE_ID?: string;
    EXPO_PUBLIC_REVENUECAT_YEARLY_PACKAGE_ID?: string;
    EXPO_PUBLIC_REVENUECAT_LIFETIME_PACKAGE_ID?: string;
    EXPO_PUBLIC_ENABLE_MOCK_PREMIUM?: string;
    EXPO_PUBLIC_SAINTSLOCK_ENABLE_SCREEN_TIME?: string;
    SAINTSLOCK_ENABLE_SCREEN_TIME?: string;
    SAINTSLOCK_ENABLE_FAMILY_CONTROLS_DEV?: string;
    SAINTSLOCK_MONTHLY?: string;
  }
}

declare const process: {
  env: NodeJS.ProcessEnv;
};
