import { RitualContentItem } from '../types/models';

export const ritualContent: RitualContentItem[] = [
  {
    id: 'psalm-be-still',
    type: 'scripture',
    title: 'Be Still',
    text: 'Be still and see that I am God.',
    reference: 'Psalm 45:11 (Douay-Rheims)',
  },
  {
    id: 'psalm-turn-eyes',
    type: 'scripture',
    title: 'Turn My Eyes',
    text: 'Turn away my eyes that they may not behold vanity: quicken thou me in thy way.',
    reference: 'Psalm 118:37 (Douay-Rheims)',
  },
  {
    id: 'psalm-hope-lord',
    type: 'scripture',
    title: 'Hope In The Lord',
    text: 'My soul hath hoped in the Lord.',
    reference: 'Psalm 129:5 (Douay-Rheims)',
  },
  {
    id: 'psalm-search-heart',
    type: 'scripture',
    title: 'Search Me',
    text: 'Search me, O God, and know my heart: examine me, and know my paths.',
    reference: 'Psalm 138:23 (Douay-Rheims)',
  },
  {
    id: 'psalm-direct-steps',
    type: 'scripture',
    title: 'Direct My Steps',
    text: 'Direct my steps according to thy word: and let no injustice have dominion over me.',
    reference: 'Psalm 118:133 (Douay-Rheims)',
  },
  {
    id: 'proverbs-look-straight',
    type: 'scripture',
    title: 'Look Straight',
    text: 'Let thy eyes look straight on, and let thy eyelids go before thy steps.',
    reference: 'Proverbs 4:25 (Douay-Rheims)',
  },
  {
    id: 'proverbs-path-feet',
    type: 'scripture',
    title: 'Straight Path',
    text: 'Make straight the path for thy feet, and all thy ways shall be established.',
    reference: 'Proverbs 4:26 (Douay-Rheims)',
  },
  {
    id: 'ecclesiastes-do-earnestly',
    type: 'scripture',
    title: 'Do It Earnestly',
    text: 'Whatsoever thy hand is able to do, do it earnestly.',
    reference: 'Ecclesiastes 9:10 (Douay-Rheims)',
  },
  {
    id: 'wisdom-seek-simplicity',
    type: 'scripture',
    title: 'Seek Him Simply',
    text: 'Think of the Lord in goodness, and seek him in simplicity of heart.',
    reference: 'Wisdom 1:1 (Douay-Rheims)',
  },
  {
    id: 'wisdom-orders-sweetly',
    type: 'scripture',
    title: 'Orders All Things',
    text: 'She reacheth therefore from end to end mightily, and ordereth all things sweetly.',
    reference: 'Wisdom 8:1 (Douay-Rheims)',
  },
  {
    id: 'sirach-service-of-god',
    type: 'scripture',
    title: 'Prepare Thy Soul',
    text: 'Son, when thou comest to the service of God, stand in justice and in fear, and prepare thy soul for temptation.',
    reference: 'Sirach 2:1 (Douay-Rheims)',
  },
  {
    id: 'sirach-turn-away',
    type: 'scripture',
    title: 'Turn Away',
    text: 'Go not after thy lusts, but turn away from thy own will.',
    reference: 'Sirach 18:30 (Douay-Rheims)',
  },
  {
    id: 'sirach-lust-flesh',
    type: 'scripture',
    title: 'Take Not Hold',
    text: 'Let not the greediness of the belly, nor lust of the flesh, take hold of me.',
    reference: 'Sirach 23:6 (Douay-Rheims)',
  },
  {
    id: 'matthew-enter-chamber',
    type: 'scripture',
    title: 'Enter Thy Chamber',
    text: 'But thou when thou shalt pray, enter into thy chamber, and having shut the door, pray to thy Father in secret.',
    reference: 'Matthew 6:6 (Douay-Rheims)',
  },
  {
    id: 'matthew-treasure-heart',
    type: 'scripture',
    title: 'Treasure And Heart',
    text: 'For where thy treasure is, there is thy heart also.',
    reference: 'Matthew 6:21 (Douay-Rheims)',
  },
  {
    id: 'matthew-watch-pray',
    type: 'scripture',
    title: 'Watch And Pray',
    text: 'Watch ye, and pray that ye enter not into temptation. The spirit indeed is willing, but the flesh weak.',
    reference: 'Matthew 26:41 (Douay-Rheims)',
  },
  {
    id: 'luke-one-thing-necessary',
    type: 'scripture',
    title: 'One Thing Necessary',
    text: 'But one thing is necessary.',
    reference: 'Luke 10:42 (Douay-Rheims)',
  },
  {
    id: 'luke-hearts-overcharged',
    type: 'scripture',
    title: 'Take Heed',
    text: 'Take heed to yourselves, lest perhaps your hearts be overcharged with surfeiting and drunkenness and the cares of this life.',
    reference: 'Luke 21:34 (Douay-Rheims)',
  },
  {
    id: 'john-light-of-life',
    type: 'scripture',
    title: 'Light Of Life',
    text: 'He that followeth me, walketh not in darkness, but shall have the light of life.',
    reference: 'John 8:12 (Douay-Rheims)',
  },
  {
    id: 'romans-instant-prayer',
    type: 'scripture',
    title: 'Instant In Prayer',
    text: 'Rejoicing in hope, patient in tribulation, instant in prayer.',
    reference: 'Romans 12:12 (Douay-Rheims)',
  },
  {
    id: 'romans-make-no-provision',
    type: 'scripture',
    title: 'No Provision',
    text: 'Put ye on the Lord Jesus Christ, and make not provision for the flesh in its concupiscences.',
    reference: 'Romans 13:14 (Douay-Rheims)',
  },
  {
    id: 'corinthians-attend-without-impediment',
    type: 'scripture',
    title: 'Without Impediment',
    text: 'I would have you to be without solicitude.',
    reference: '1 Corinthians 7:32 (Douay-Rheims)',
  },
  {
    id: 'corinthians-way-to-bear',
    type: 'scripture',
    title: 'Way To Bear It',
    text: 'God is faithful, who will not suffer you to be tempted above that which you are able: but will make also with temptation issue, that you may be able to bear it.',
    reference: '1 Corinthians 10:13 (Douay-Rheims)',
  },
  {
    id: 'galatians-walk-in-spirit',
    type: 'scripture',
    title: 'Walk In The Spirit',
    text: 'Walk in the spirit, and you shall not fulfil the lusts of the flesh.',
    reference: 'Galatians 5:16 (Douay-Rheims)',
  },
  {
    id: 'ephesians-redeeming-time',
    type: 'scripture',
    title: 'Redeeming The Time',
    text: 'Redeeming the time, because the days are evil.',
    reference: 'Ephesians 5:16 (Douay-Rheims)',
  },
  {
    id: 'philippians-think-on-these',
    type: 'scripture',
    title: 'Think On These Things',
    text: 'For the rest, brethren, whatsoever things are true, whatsoever modest, whatsoever just, whatsoever holy, whatsoever lovely, whatsoever of good fame, if there be any virtue, if any praise of discipline, think on these things.',
    reference: 'Philippians 4:8 (Douay-Rheims)',
  },
  {
    id: 'colossians-things-above',
    type: 'scripture',
    title: 'Things Above',
    text: 'Mind the things that are above, not the things that are upon the earth.',
    reference: 'Colossians 3:2 (Douay-Rheims)',
  },
  {
    id: 'colossians-watch-in-prayer',
    type: 'scripture',
    title: 'Watch In Prayer',
    text: 'Be instant in prayer: watching in it with thanksgiving.',
    reference: 'Colossians 4:2 (Douay-Rheims)',
  },
  {
    id: 'timothy-sobriety',
    type: 'scripture',
    title: 'Spirit Of Sobriety',
    text: 'For God hath not given us the spirit of fear: but of power, and of love, and of sobriety.',
    reference: '2 Timothy 1:7 (Douay-Rheims)',
  },
  {
    id: 'hebrews-looking-on-jesus',
    type: 'scripture',
    title: 'Looking On Jesus',
    text: 'Looking on Jesus, the author and finisher of faith.',
    reference: 'Hebrews 12:2 (Douay-Rheims)',
  },
  {
    id: 'james-ask-wisdom',
    type: 'scripture',
    title: 'Ask Wisdom',
    text: 'If any of you want wisdom, let him ask of God, who giveth to all men abundantly, and upbraideth not.',
    reference: 'James 1:5 (Douay-Rheims)',
  },
  {
    id: 'james-draw-nigh',
    type: 'scripture',
    title: 'Draw Nigh',
    text: 'Draw nigh to God, and he will draw nigh to you.',
    reference: 'James 4:8 (Douay-Rheims)',
  },
  {
    id: 'peter-be-sober',
    type: 'scripture',
    title: 'Be Sober And Watch',
    text: 'Be sober and watch: because your adversary the devil, as a roaring lion, goeth about seeking whom he may devour.',
    reference: '1 Peter 5:8 (Douay-Rheims)',
  },
  {
    id: 'john-love-not-world',
    type: 'scripture',
    title: 'Love Not The World',
    text: 'Love not the world, nor the things which are in the world.',
    reference: '1 John 2:15 (Douay-Rheims)',
  },
  {
    id: 'steady-heart-prayer',
    type: 'prayer',
    title: 'Steady My Heart',
    text: 'Lord Jesus Christ, steady my heart and order my desires.',
  },
  {
    id: 'quiet-obedience-prayer',
    type: 'prayer',
    title: 'Quiet Obedience',
    text: 'Let this pause become obedience, not performance.',
  },
  {
    id: 'guard-my-eyes-prayer',
    type: 'prayer',
    title: 'Guard My Eyes',
    text: 'Guide my eyes, my thoughts, and my time toward what is clean and fruitful.',
  },
  {
    id: 'seek-eternal-prayer',
    type: 'prayer',
    title: 'Seek What Lasts',
    text: 'Teach me to seek what is eternal before what is easy.',
  },
  {
    id: 'rule-of-life-prayer',
    type: 'prayer',
    title: 'Rule Of Life',
    text: 'Make my phone serve my calling, not govern my attention.',
  },
];
